version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    restart: always

  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
